"""Presentation formats for routed dashboard action files.

The analytical pipeline may continue to create CSV files internally.  At the
publication boundary, projects can request Excel-compatible XLSX workbooks so
end users are not exposed to locale-dependent CSV delimiter handling.
"""
from __future__ import annotations

import csv
import math
import re
import zipfile
from pathlib import Path
from xml.sax.saxutils import escape, quoteattr

SUPPORTED_ACTION_FILE_FORMATS = {"csv", "xlsx"}


def action_file_format(config: dict) -> str:
    raw = (config.get("action_files") or {}).get("format", "csv")
    value = str(raw).strip().lower()
    if value == "xls":
        # Do not emit the obsolete binary .xls format. Treat the familiar name
        # as a request for a modern Excel workbook.
        value = "xlsx"
    if value not in SUPPORTED_ACTION_FILE_FORMATS:
        raise ValueError("action_files.format must be csv or xlsx")
    return value


def delivered_filename(name: str, fmt: str) -> str:
    fmt = str(fmt).lower()
    path = Path(name)
    if fmt == "xlsx" and path.suffix.lower() == ".csv":
        return path.with_suffix(".xlsx").name
    return path.name


def _column_name(index: int) -> str:
    out = ""
    while index:
        index, rem = divmod(index - 1, 26)
        out = chr(65 + rem) + out
    return out


def _cell_xml(ref: str, value: str, style: int = 0) -> str:
    # Store action-list values as inline strings. This deliberately preserves
    # participant IDs, leading zeroes, date strings and coded values exactly as
    # generated by the validated analysis pipeline rather than letting Excel
    # silently coerce them on open.
    text = "" if value is None else str(value)
    preserve = ' xml:space="preserve"' if text != text.strip() else ""
    style_attr = f' s="{style}"' if style else ""
    return (
        f'<c r="{ref}" t="inlineStr"{style_attr}>'
        f'<is><t{preserve}>{escape(text)}</t></is></c>'
    )


def csv_to_xlsx(source: Path, destination: Path, sheet_name: str = "Action list") -> None:
    """Convert a delimited text table to a deterministic, dependency-free XLSX.

    The workbook contains one worksheet, a bold frozen header row, autofilter,
    and readable column widths.  ZIP member timestamps are fixed so identical
    CSV input produces identical XLSX bytes and therefore stable SHA-256 hashes.
    """
    source = Path(source)
    destination = Path(destination)
    destination.parent.mkdir(parents=True, exist_ok=True)

    sample = source.read_text(encoding="utf-8-sig", errors="strict")
    try:
        dialect = csv.Sniffer().sniff(sample[:65536], delimiters=",;\t|")
    except csv.Error:
        dialect = csv.excel

    rows = list(csv.reader(sample.splitlines(), dialect))
    max_cols = max((len(r) for r in rows), default=0)
    if max_cols == 0:
        rows = [[]]

    widths = []
    for col in range(max_cols):
        width = max((len(str(r[col])) if col < len(r) else 0 for r in rows), default=0)
        widths.append(min(max(width + 2, 10), 45))

    sheet_name = re.sub(r"[\\/*?:\[\]]", "_", sheet_name)[:31] or "Action list"
    last_ref = f"{_column_name(max_cols)}{max(len(rows), 1)}" if max_cols else "A1"

    row_xml = []
    for r_idx, row in enumerate(rows, 1):
        cells = []
        for c_idx in range(1, max_cols + 1):
            value = row[c_idx - 1] if c_idx <= len(row) else ""
            cells.append(_cell_xml(f"{_column_name(c_idx)}{r_idx}", value, 1 if r_idx == 1 else 0))
        row_xml.append(f'<row r="{r_idx}">{"".join(cells)}</row>')

    cols_xml = "".join(
        f'<col min="{i}" max="{i}" width="{width}" customWidth="1"/>'
        for i, width in enumerate(widths, 1)
    )
    auto_filter = f'<autoFilter ref="A1:{last_ref}"/>' if rows and max_cols else ""
    sheet = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
        f'<dimension ref="A1:{last_ref}"/>'
        '<sheetViews><sheetView workbookViewId="0">'
        '<pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/>'
        '</sheetView></sheetViews>'
        '<sheetFormatPr defaultRowHeight="15"/>'
        f'<cols>{cols_xml}</cols>' if cols_xml else ''
    )
    # The conditional expression above cannot safely span XML concatenation;
    # build the tail separately for clarity.
    sheet = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
        f'<dimension ref="A1:{last_ref}"/>'
        '<sheetViews><sheetView workbookViewId="0">'
        '<pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/>'
        '</sheetView></sheetViews>'
        '<sheetFormatPr defaultRowHeight="15"/>'
        + (f'<cols>{cols_xml}</cols>' if cols_xml else '')
        + f'<sheetData>{"".join(row_xml)}</sheetData>'
        + auto_filter
        + '</worksheet>'
    )

    content_types = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
<Default Extension="xml" ContentType="application/xml"/>
<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>
</Types>'''
    root_rels = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>'''
    workbook = f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
<sheets><sheet name={quoteattr(sheet_name)} sheetId="1" r:id="rId1"/></sheets>
</workbook>'''
    workbook_rels = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>'''
    styles = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><name val="Calibri"/></font></fonts>
<fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills>
<borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders>
<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>
<cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/></cellXfs>
<cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles>
</styleSheet>'''

    members = {
        "[Content_Types].xml": content_types,
        "_rels/.rels": root_rels,
        "xl/workbook.xml": workbook,
        "xl/_rels/workbook.xml.rels": workbook_rels,
        "xl/styles.xml": styles,
        "xl/worksheets/sheet1.xml": sheet,
    }
    fixed_time = (1980, 1, 1, 0, 0, 0)
    with zipfile.ZipFile(destination, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for name in sorted(members):
            info = zipfile.ZipInfo(name, fixed_time)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o600 << 16
            zf.writestr(info, members[name].encode("utf-8"))


def stage_action_file(source: Path, destination: Path, fmt: str) -> None:
    source = Path(source)
    destination = Path(destination)
    if fmt == "xlsx" and source.suffix.lower() == ".csv":
        csv_to_xlsx(source, destination)
    else:
        destination.parent.mkdir(parents=True, exist_ok=True)
        # copyfile is intentional: no source metadata is needed in a recipient package.
        import shutil
        shutil.copyfile(source, destination)
