#!/usr/bin/env bash
# Quarto Dashboard Delivery System 1.0.0
# Copyright (c) 2026 Chrissy h. Roberts — MIT License
set -euo pipefail

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$BASE_DIR/config"
DASHBOARDS_DIR="$BASE_DIR/dashboards"
LOG_DIR="$BASE_DIR/logs"
VENV="$BASE_DIR/.venv"

mkdir -p "$CONFIG_DIR" "$DASHBOARDS_DIR" "$LOG_DIR"
umask 077

echo "Quarto Dashboard Delivery System 1.0.0 setup"
echo "============================================"
echo

need() {
  command -v "$1" >/dev/null 2>&1
}

install_rclone() {
  if need rclone; then
    echo "✓ rclone already installed: $(command -v rclone)"
    return
  fi
  echo
  echo "rclone is not installed."
  read -r -p "Install rclone now using its official Linux/macOS installer? [y/N]: " ans
  case "${ans:-N}" in
    y|Y)
      if need curl; then
        echo "Installing rclone..."
        curl -fsSL https://rclone.org/install.sh | sudo bash
      else
        echo "curl is not installed. Ask IT to install rclone, then rerun setup."
        return 1
      fi
      ;;
    *)
      echo "Skipping rclone. Local-only delivery will still work."
      ;;
  esac
}

if ! need python3; then
  echo "ERROR: Python 3 is required. Please ask IT to install python3 and python3-venv." >&2
  exit 2
fi
echo "✓ Python: $(python3 --version)"

if ! python3 -m venv --help >/dev/null 2>&1; then
  echo "ERROR: Python venv support is missing." >&2
  echo "On Debian/Ubuntu this is usually provided by the python3-venv package."
  exit 2
fi

if [[ ! -d "$VENV" ]]; then
  echo "Creating persistent Python virtual environment..."
  python3 -m venv "$VENV"
fi
echo "✓ Python environment: $VENV"

"$VENV/bin/python" -m pip install --upgrade pip
"$VENV/bin/python" -m pip install -r "$BASE_DIR/requirements.txt"
echo "✓ Python dependencies installed"

if need quarto; then
  echo "✓ Quarto: $(quarto --version | head -1)"
else
  echo
  echo "WARNING: Quarto was not found on PATH."
  echo "Install Quarto before attempting a render:"
  echo "  https://quarto.org/docs/get-started/"
fi

echo
read -r -p "Will any project deliver to SharePoint? [y/N]: " sp
case "${sp:-N}" in
  y|Y) install_rclone || true ;;
  *) echo "Skipping SharePoint/rclone setup." ;;
esac

touch "$CONFIG_DIR/secrets.env"
chmod 600 "$CONFIG_DIR/secrets.env"
touch "$CONFIG_DIR/rclone.conf"
chmod 600 "$CONFIG_DIR/rclone.conf"

# Store executable locations (not credentials) so cron does not depend on an
# interactive shell PATH. This file is safe to inspect and edit.
{
  echo "# Generated by setup.sh; contains executable paths only."
  if need quarto; then printf 'QUARTO_BIN=%q\n' "$(command -v quarto)"; fi
  if need rclone; then printf 'RCLONE_BIN=%q\n' "$(command -v rclone)"; fi
} > "$CONFIG_DIR/runtime.env"
chmod 644 "$CONFIG_DIR/runtime.env"
echo "✓ Protected configuration files created"

chmod +x "$BASE_DIR/run.sh" "$BASE_DIR/dashboardctl" "$BASE_DIR/setup.sh"

echo
echo "Setup complete."
echo
echo "Next steps:"
echo "  1. Put each Quarto project directly inside:"
echo "       $DASHBOARDS_DIR"
echo "  2. Configure each project:"
echo "       ./dashboardctl add-project"
echo "  3. If using SharePoint:"
echo "       ./dashboardctl sharepoint"
echo "  4. Validate:"
echo "       ./dashboardctl validate"
echo "  5. Test one project:"
echo "       ./dashboardctl test PROJECT_FOLDER"
echo "  6. When happy, install cron:"
echo "       ./dashboardctl cron"
